extends:
  - spectral:oas

rules:
  no-swagger-version:
    description: Swagger version detected. Please use OpenAPI version 3.0.* instead
    given: $.swagger
    severity: error
    then:
      function: falsy

  ensure-openapi-version-3:
    description: OpenAPI version should be 3.0.*
    given: $.openapi
    severity: error
    then:
      function: pattern
      functionOptions:
        match: ^3\.0
